from pathlib import Path

PROGRAM_VERSION = "1.0.0"
CONFIG_VERSION = 1

BASE_DIR = Path("WebTMData")

STOKEN_MOSAIC = "*" * 6
BDUSS_MOSAIC = STOKEN_MOSAIC * 3


CONFIRM_EXPIRE = 86400
CONTENT_VALID_EXPIRE = 86400
PID_CACHE_EXPIRE = 86400 * 7
CODE_EXPIRE = 86400

PROGRAM_NAME = "WebTM"
LOG_FILE_NAME = "webtm.log"
LOG_DIR = BASE_DIR / "logs"

USER_DIR = BASE_DIR / "users"

DEFAULT_SERVER_PORT = 36799


for i in [LOG_DIR, USER_DIR]:
    if not i.exists():
        i.mkdir(parents=True)
